AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  This project consist of launching an ec2 instance using apache and a DNS in route53. 
  Instead of using a default DNS giving by ec2, this apache will display the message using a custon DNS. 

Mappings:
  RegionMap:
    us-east-1:
      AMI: "ami-08a0d1e16fc3f61ea"
    us-east-2:
      AMI: "ami-033fabdd332044f06"
    us-west-1:
      AMI: "ami-0ca1f30768d0cf0e1"
    us-west-2:
      AMI: "ami-0b20a6f09484773af"
    eu-west-1:
      AMI: "ami-0551ce4d67096d606"
    sa-east-1:
      AMI: "ami-0df032b0fbc220383"
    ap-southeast-1:
      AMI: "ami-04c913012f8977029"
    ap-southeast-2:
      AMI: "ami-0e326862c8e74c0fe"
    ap-northeast-1:
      AMI: "ami-0f9fe1d9214628296"

Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
      - t2.medium
      - t3.nano
      - t3.micro
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.

Resources:
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      InstanceType: !Ref InstanceTypeParameter
      KeyName: awesome-key-east1           # Replace with your key pair name
      SecurityGroups:
        - !ImportValue
            Mystack-route53-ec2-SecurityGroupID
      SubnetId: 
          !ImportValue 'Mystack-route53-ec2-SubnetID'    
      VpcId: 
          !ImportValue 'Mystack-route53-ec2-VPCID'
      Tags:
       - Key: Name
         Value: ec2-route53-server
      UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install httpd -y
            echo "<html><body><h1>HELLO THIS SERVER WAS BUILD WITH A CUSTON DNS. 
            It's was made by Justo Mebodo using cloudformation template</h1></body></html>" > /var/www/html/index.html
            systemctl start httpd
            systemctl enable httpd       

  Route53HostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: 'justoaws.com'

  Route53RecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref Route53HostedZone
      Name: 'justoaws.com'
      Type: 'A'
      TTL: '60'
      ResourceRecords:
        - !GetAtt 'MyEC2Instance.PublicIp'
Outputs:
  InstanceId:
    Description: 'Instance ID of the newly created EC2 instance'
    Value: !Ref MyEC2Instance
  PublicIP:
    Description: 'Public IP address of the newly created EC2 instance'
    Value: !GetAtt MyEC2Instance.PublicIp
  WebsiteURL:
    Description: 'URL of the website'
    Value: !Join ['', ['http://', justoaws.com]]
  